[[constraint]]
  name = "gitlab.com/24sessions/lib-go-logger"
  source = "git@gitlab.com:24sessions/lib-go-logger.git"
  version = "~0.3.1"

[[constraint]]
  name = "gitlab.com/24sessions/lib-beego-logger"
  source = "git@gitlab.com:24sessions/lib-beego-logger.git"
  version = "~0.1"

[[constraint]]
  name = "gitlab.com/24sessions/sdk-go-configurator"
  source = "git@gitlab.com:24sessions/sdk-go-configurator.git"
  version = "~0.2.2"

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.11.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.16"

[[constraint]]
  branch = "master"
  name = "github.com/spacemonkeygo/openssl"

[[constraint]]
  name = "github.com/youmark/pkcs8"
  version = "^1.1"

[prune]
  go-tests = true
  unused-packages = true
